name: Tuist Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version for the release (ex. x.x.x)
        required: true
      title:
        description: Title for the release (ex. Chimera)
        required: true

env:
  RUBY_VERSION: '3.0.3'
  TUIST_STATS_OPT_OUT: true

jobs:
  release:
    runs-on: macOS-11
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ env.RUBY_VERSION }}-gems-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.RUBY_VERSION }}-gems-
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Update Tuist version
      # This step updates the version in the Constants.swift file by replacing the current tag in Constants.swift with the tagged release.
      # This step also updates the CHANGELOG.md to rename the Next section to the proper release version.
      run: |
        sed -i '' -e "s/version = \".*\"/version = \"${{ github.event.inputs.version }}\"/g" Sources/TuistSupport/Constants.swift
        sed -i '' -e "s/## Next/## ${{ github.event.inputs.version }} - ${{ github.event.inputs.title }}/g" CHANGELOG.md
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[Release] Tuist ${{ github.event.inputs.version }} - ${{ github.event.inputs.title }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}